type AlternativeBadgeTone = 'default' | 'secondary' | 'success' | 'warning' | 'info';
type TranslateFn = (key: string, options?: Record<string, unknown>) => string;

const TAG_KEYS: Record<string, string> = {
  requested_mode: 'optimizer.tagRequestedMode',
  diversity: 'optimizer.tagDiversity',
  auto_generated: 'optimizer.tagAutoGenerated',
  fallback: 'optimizer.tagFallback',
  budget: 'optimizer.tagBudget',
  stable: 'optimizer.tagStable',
  feed_exclusion: 'optimizer.tagFeedExclusion',
  lowest_cost: 'optimizer.tagLowestCost',
  widest_mix: 'optimizer.tagWidestMix',
};

const STRATEGY_KEYS: Record<string, string> = {
  priority_tiered_balance: 'optimizer.strategyTieredBalance',
  single_pass_balance: 'optimizer.strategySinglePassBalance',
  minimize_cost: 'optimizer.strategyMinimizeCost',
  bounded_fixed_feed_balance: 'optimizer.strategyBoundedFixedFeedBalance',
  fixed_feeds: 'optimizer.strategyFixedFeeds',
  repair_with_additions: 'optimizer.strategyRepairWithAdditions',
  library_constructor: 'optimizer.strategyLibraryConstructor',
  current_state: 'optimizer.strategyCurrentState',
  single: 'optimizer.strategySingle',
  starter_plan: 'optimizer.strategyStarterPlan',
};

function prettifyToken(token: string): string {
  return token
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export function alternativeDisplayLabel(index: number, t: TranslateFn): string {
  return index === 0
    ? t('optimizer.currentRation')
    : t('optimizer.rationN', { n: index + 1 });
}

export function localizeAlternativeTag(tag: string, t: TranslateFn): string {
  const key = TAG_KEYS[tag];
  return key ? t(key) : prettifyToken(tag);
}

export function localizeAlternativeStrategy(strategy: string, t: TranslateFn): string {
  return strategy
    .split('+')
    .filter(Boolean)
    .map((part) => {
      const key = STRATEGY_KEYS[part];
      return key ? t(key) : prettifyToken(part);
    })
    .join(' + ');
}

export function alternativeTagTone(tag: string): AlternativeBadgeTone {
  switch (tag) {
    case 'requested_mode':
      return 'info';
    case 'diversity':
    case 'widest_mix':
      return 'success';
    case 'budget':
    case 'lowest_cost':
      return 'warning';
    case 'fallback':
    case 'feed_exclusion':
      return 'secondary';
    default:
      return 'default';
  }
}
